config/routes.rb
Rails.application.routes.draw do
  # devise_for :order_details
  # devise_for :orders
  # devise_for :cart_items
  # devise_for :genres
  # devise_for :customers
  # devise_for :items
  # devise_for :admins
  # devise_for :addresses



  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  get 'about'=>'public/homes#about',as:'about'
  root to: 'public/homes#top'
  scope module: :public do
  resources :items
  get 'orders/complete'=>'orders#complete'
  post 'orders/confirm'=>'orders#confirm', as:'confirm'
  get 'customers/mypage' => 'customers#show', as:'mypage'
  get 'customers/information/edit' => 'customers#edit', as:'customer_edit'
  patch 'customers/information' => 'customers#update', as:'information'
  resources :orders
  delete 'cart_items/destroy_all'=>'cart_items#destroy_all'
  resources :cart_items
  resources :addresses
  get 'customers/unsubscribe'=>'customers#unsubscribe'
  patch 'customers/withdraw'=>'customers#withdraw'
  end

   namespace :admin do
     root to: 'homes#top'
     resources :items

     resources :customers
     resources :orders, only: [:show, :update]
   end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable

  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable

  has_one_attached :image
  belongs_to :item
  belongs_to :customer


  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :cart_items

  has_many :addresses
  has_many :orders

end

app/models/genre.rb
class Genre < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable
end

app/models/item.rb
class Item < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width,height]).processed
  end

  # def add_tax_price
  #       (self.price * 1.10).round
  # end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable
  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum order_status: {
     nyuukinnmachi:0, nyuukinnkakuninn:1, seisakuchuu:2, hassouzyunnbichuu:3, hassouzumi:4
  }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable
  
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all.page(params[:page]).per(10)
    @amount = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(5)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(items_params)

    if @item.save
      redirect_to admin_item_path(@item.id), notice:"Item was successfully updated."
    else
      @items = Item.all
      render :index
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(items_params)
    redirect_to admin_item_path(@item), notice:"Item was successfully updated."
    else
    render:edit
    end
  end

  private
  def items_params
    params.require(:item).permit(:image, :name, :introduction, :gener_id, :price, :is_active)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?



  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/items/edit.html.erb
<div class = "container">
<h2>商品編集</h2>


<%= form_with model: @item, url:admin_item_path(@item.id), method: :patch do |f| %>
<table>
<tbody>
 <tr>
　<td>商品画像</td>
  <td><%= f.file_field :image %></td>
 </tr>
 <tr>
  <td>商品名</td>
  <td><%= f.text_field :name %></td>
 </tr>
 <tr>
  <td>商品説明</td>
  <td><%= f.text_area :introduction %></td>
 </tr>

 <!--<h4>ジャンル</h4>-->
 <!--</%= f.select :gener_id %>-->
 <tr>
  <td>税抜価格</td>
  <td><%= f.text_field :price %> 円</td>
 </tr>
 <tr>
  <td>販売ステータス</td>
  <td><%= f.radio_button :is_active, true %>販売中
      <%= f.radio_button :is_active, false %>販売停止中
  </td>
 </tr>
</tbody>
</table>

 <%= f.submit '変更を保存する' %>
<% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container">
<h4>商品一覧</h4>
<div class="row">
<table>
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <!--<th>ジャンル</th>-->
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to admin_item_path(item.id) do %>
        <%= item.name %>
        <% end %>
        </td>
        <td><%= item.price %></td>
        <!--<td></%= item.genre_id %></td>-->
        <td><% if item.is_active==true %>
            販売中
            <% else %>
            販売停止中
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "新規作成", new_admin_item_path %>
</div>
<%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class = "container">
<h2>商品新規登録</h2>


 <%= form_with model: @item, url:admin_items_path, method: :post do |f| %>
<table>
 <tbody>
 <tr>
  <td>商品画像</td>
  <td><%= f.file_field :image %></td>
 </tr>

 <tr>
  <td>商品名</td>
  <td><%= f.text_field :name %></td>
 </tr>

 <tr>
  <td>商品説明</td>
  <td><%= f.text_area :introduction %></td>
 </tr>
 <!--<h4>ジャンル</h4>-->
 <!--</%= f.select :gener_id %>-->

 <tr>
  <td>税抜価格</td>
  <td><%= f.text_field :price %> 円</td>
 </tr>

 <tr>
  <td>販売ステータス</td>
  <td><%= f.radio_button :is_active, true %>販売中
      <%= f.radio_button :is_active, false %>販売停止中
  </td>
 </tr>
 </tbody>
</table>
 <%= f.submit '新規登録' %>
<% end %>
</div>

app/views/admin/items/show.html.erb
<div class = "container">
<h2>商品詳細</h2>
<div class="row">
<div class="col-lg-3">
 <%= image_tag @item.get_image(130,130) %>
</div>

<div class="col-lg-9">
<table>
<thead>
  <tr>
  <th>商品名</th>
  <th>商品説明</th>
  <th>税込価格(税抜価格)</th>
  <th>販売ステータス<th>
  </tr>
</thead>
<tbody>
  <tr>
   <th><%= @item.name %></th>


   <th><%= @item.introduction %></th>

<!--<h4>ジャンル</h4>-->
<!--<p></%= @item.gener_id %></p>-->


   <th><%= @item.with_tax_price %>(<%= @item.price %>)</th>


   <th><% if @item.is_active==true %>
        販売中
      <% else %>
        販売停止中
      <% end %>
   </th>
  </tr>
</tbody>
</table>


<%= link_to "編集する", edit_admin_item_path(@item.id) %>
</div>
</div>
</div>