config/routes.rb
Rails.application.routes.draw do
  # devise_for :order_details
  # devise_for :orders
  # devise_for :cart_items
  # devise_for :genres
  # devise_for :customers
  # devise_for :items
  # devise_for :admins
  # devise_for :addresses



  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  get 'about'=>'public/homes#about',as:'about'
  root to: 'public/homes#top'
  scope module: :public do
  resources :items
  get 'orders/complete'=>'orders#complete'
  post 'orders/confirm'=>'orders#confirm', as:'confirm'
  get 'customers/mypage' => 'customers#show', as:'mypage'
  get 'customers/information/edit' => 'customers#edit', as:'customer_edit'
  patch 'customers/information' => 'customers#update', as:'information'
  resources :orders
  delete 'cart_items/destroy_all'=>'cart_items#destroy_all'
  resources :cart_items
  resources :addresses
  get 'customers/unsubscribe'=>'customers#unsubscribe'
  patch 'customers/withdraw'=>'customers#withdraw'
  end

   namespace :admin do
     root to: 'homes#top'
     resources :items

     resources :customers
     resources :orders, only: [:show, :update]
   end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable

  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable

  has_one_attached :image
  belongs_to :item
  belongs_to :customer


  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :cart_items

  has_many :addresses
  has_many :orders

end

app/models/genre.rb
class Genre < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable
end

app/models/item.rb
class Item < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width,height]).processed
  end

  # def add_tax_price
  #       (self.price * 1.10).round
  # end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable
  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum order_status: {
     nyuukinnmachi:0, nyuukinnkakuninn:1, seisakuchuu:2, hassouzyunnbichuu:3, hassouzumi:4
  }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable
  
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customers_params)
    redirect_to admin_customer_path(@customer), notice:"Item was successfully updated."
    else
    render:edit
    end
  end

  private
  def customers_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :encrypted_password,  :email, :is_deleted)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all.page(params[:page]).per(10)
    @amount = 0
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?



  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/customers/edit.html.erb
<div class = "container">
<h2><%= @customer.last_name %> <%= @customer.first_name %>会員情報編集</h2>
<!--<div class="row">-->
<table>
<tbody>
<%= form_with model: @customer, url:admin_customer_path(@customer.id), method: :patch do |f| %>
 <tr>
　<td>会員ID</td>
  <td><%= @customer.id %></td>
 </tr>

 <tr>
  <td>氏名</td>
  <td><%= f.text_field :last_name %>
      <%= f.text_field :first_name %>
  </td>
 </tr>

 <tr>
  <td>フリガナ</td>
  <td><%= f.text_field :last_name_kana %>
      <%= f.text_field :first_name_kana %>
  </td>
 </tr>

 <tr>
  <td>郵便番号</td>
  <td><%= f.text_field :postal_code %></td>
 </tr>

 <tr>
  <td>住所</td>
  <td><%= f.text_field :address %></td>
 </tr>

 <tr>
  <td>電話番号</td>
  <td><%= f.text_field :telephone_number %></td>
 </tr>

 <tr>
  <td>メールアドレス</td>
  <td><%= f.text_field :email %></td>
 </tr>

 <tr>
  <td>会員ステータス</td>
  <td><%= f.radio_button :is_deleted, false %>有効
      <%= f.radio_button :is_deleted, true %>退会
  </td>
 </tr>
</tbody>
</table>

 <%= f.submit '変更を保存' %>
<% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
<h4>会員一覧</h4>
<div class="row">

<table>
  <thead>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= link_to admin_customer_path(customer.id) do %>
        <%= customer.last_name %>
        <%= customer.first_name %>
        <% end %>
        </td>
        <td><%= customer.email %></td>
        <td><% if customer.is_deleted==true %>
            退会
            <% else %>
            有効
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class = "container">
<h2><%= @customer.last_name %> <%= @customer.first_name %>会員詳細</h2>
<table>
<tbody>
  <tr>
   <td>会員ID</td>
   <td><%= @customer.id %></td>
  </tr>

  <tr>
   <td>氏名</td>
   <td><%= @customer.last_name %>
       <%= @customer.first_name %>
   </td>
  </tr>

  <tr>
   <td>フリガナ</td>
   <td><%= @customer.last_name_kana %>
       <%= @customer.first_name_kana %>
   </td>
  </tr>

  <tr>
   <td>郵便番号</td>
   <td><%= @customer.postal_code %></td>
  </tr>

  <tr>
   <td>住所</td>
   <td><%= @customer.address %></td>
  </tr>

  <tr>
   <td>電話番号</td>
   <td><%= @customer.telephone_number %></td>
  </tr>

  <tr>
   <td>メールアドレス</td>
   <td><%= @customer.email %></td>
  </tr>

  <tr>
   <td>会員ステータス</td>
   <td><% if @customer.is_deleted==true %>
        退会
      <% else %>
        有効
      <% end %>
   </td>
  </tr>
</tbody>
</table>


<%= link_to "編集する", edit_admin_customer_path(@customer.id) %>
<%= link_to "注文履歴一覧を見る", admin_root_path %>
</div>