config/routes.rb
Rails.application.routes.draw do
  # devise_for :order_details
  # devise_for :orders
  # devise_for :cart_items
  # devise_for :genres
  # devise_for :customers
  # devise_for :items
  # devise_for :admins
  # devise_for :addresses



  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  get 'about'=>'public/homes#about',as:'about'
  root to: 'public/homes#top'
  scope module: :public do
  resources :items
  get 'orders/complete'=>'orders#complete'
  post 'orders/confirm'=>'orders#confirm', as:'confirm'
  get 'customers/mypage' => 'customers#show', as:'mypage'
  get 'customers/information/edit' => 'customers#edit', as:'customer_edit'
  patch 'customers/information' => 'customers#update', as:'information'
  resources :orders
  delete 'cart_items/destroy_all'=>'cart_items#destroy_all'
  resources :cart_items
  resources :addresses
  get 'customers/unsubscribe'=>'customers#unsubscribe'
  patch 'customers/withdraw'=>'customers#withdraw'
  end

   namespace :admin do
     root to: 'homes#top'
     resources :items

     resources :customers
     resources :orders, only: [:show, :update]
   end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable

  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable

  has_one_attached :image
  belongs_to :item
  belongs_to :customer


  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :cart_items

  has_many :addresses
  has_many :orders

end

app/models/genre.rb
class Genre < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable
end

app/models/item.rb
class Item < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width,height]).processed
  end

  # def add_tax_price
  #       (self.price * 1.10).round
  # end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable
  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum order_status: {
     nyuukinnmachi:0, nyuukinnkakuninn:1, seisakuchuu:2, hassouzyunnbichuu:3, hassouzumi:4
  }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable
  
  belongs_to :order
  belongs_to :item
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?



  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ながのCAKE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
       <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container">
              <%= link_to "LOGO", root_path %>
             <div class="navbar-collapse collapse" id="navbarNavDropdown" style>
              <% if customer_signed_in? %>
               <ul class="navbar-nav ml-auto">
                 <li>
                  <%= link_to "マイページ", mypage_path %>

                 </li>
                 <li>
                  <%= link_to "商品一覧", items_path %>

                 </li>
                 <li>
                  <%= link_to "カート", cart_items_path %>

                 </li>
                 <li>
                  <%= link_to "ログアウト", destroy_customer_session_path,method: :delete %>
                 </li>
               </ul>
              <% elsif admin_signed_in? %>
               <ul class="navbar-nav ml-auto">
                 <li>
                  <%= link_to "商品一覧", admin_items_path %>

                 </li>
                 <li>
                  <%= link_to "会員一覧", admin_customers_path %>

                 </li>
                 <li>
                  <%= link_to "注文履歴一覧", admin_root_path %>

                 </li>
                 <li>
                  <%= link_to "ログアウト", destroy_admin_session_path,method: :delete %>

                 </li>
               </ul>
              <% else %>
               <ul class="navbar-nav ml-auto">
                 <li>
                 <%= link_to "About", about_path %>

                 </li>
                  <li>
                  <%= link_to "商品一覧", items_path %>

                 </li>
                 <li>
                  <%= link_to "新規登録", new_customer_registration_path %>

                 </li>
                 <li>
                  <%= link_to "ログイン", new_customer_session_path %>

                 </li>
               </ul>
              <% end %>
             </div>
          </div>
       </nav>

    </header>
    <%= flash[:notice] %>

    <%= yield %>